# Generated by Django 5.1.4 on 2025-01-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='oreder',
            new_name='order',
        ),
    ]
